//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servers.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seerver
    {
        public Seerver()
        {
            this.Userr = new HashSet<Userr>();
        }
    
        public int Id { get; set; }
        public string Name_server { get; set; }
        public string Adres { get; set; }
    
        public virtual ICollection<Userr> Userr { get; set; }
    }
}
